import type { Metadata } from "next";
import Navbar from "@/components/NavBar2/NavBar";
import Footer from "@/components/Footer/Footer";
import "./globals.css";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className="flex flex-col w-screen h-screen antialiased">
                <Navbar />

                <main className="overflow-y-auto mt-[64px]">
                    {children}
                </main>

                <Footer />
            </body>
        </html>
    );
}
